import React from 'react';
import { Section, Container, Badge } from '@nooha/ui';
import { constructMetadata } from '@/config/seo';
import * as motion from 'framer-motion/client';

export const metadata = constructMetadata({
  title: 'Terms of Service',
  description: 'Terms of Service governing the use of Nooha Labs platforms, software, and ecosystems.',
  path: '/terms',
});

export default function TermsPage() {
  return (
    <Section className="pt-32 pb-32 relative overflow-hidden">
      <div className="absolute top-0 left-0 w-full h-px bg-gradient-to-r from-transparent via-emerald-500/20 to-transparent" />

      <Container className="max-w-4xl relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          <Badge variant="outline" className="mb-6 border-emerald-500/20 text-emerald-500 font-black tracking-[0.2em]">Service Framework</Badge>
          <h1 className="text-4xl md:text-7xl font-extrabold text-white tracking-tighter">Terms of Service</h1>
          <p className="mt-4 text-[10px] font-black uppercase tracking-[0.4em] text-zinc-500">Last updated: July 30, 2024</p>
        </motion.div>

        <div className="mt-16 space-y-16 text-zinc-400 leading-relaxed font-medium">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.3 }}
            className="p-10 rounded-[2.5rem] bg-[#111827]/40 border border-[#1E293B] shadow-inner"
          >
            <p className="text-zinc-200 text-lg leading-relaxed">
              Welcome to Nooha Labs. By accessing our platform, utilizing our proprietary software products, or integrating via our API services, you agree to comply with and be bound by the following professional service terms.
            </p>
          </motion.div>

          <section className="space-y-6">
            <h2 className="text-2xl font-bold text-white tracking-tight">1. Software Licensing & Intellectual Property</h2>
            <p className="text-zinc-500">
              All custom software, branding tokens, neural architectures, and source code generated by **Nooha Labs Ltd** remains protected under international copyright and intellectual property framework agreements. Client organizations are granted non-exclusive, non-transferable usage licenses as explicitly defined in their individual Service Level Agreements (SLAs).
            </p>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl font-bold text-white tracking-tight">2. Acceptable Operational Use</h2>
            <p className="text-zinc-500">
              Users and institutional partners must not misuse our ecosystem, attempt unauthorized database penetration (SQLi, XSS), or violate multi-tenant isolation rules. Automated scraping, data harvesting, or reverse engineering of Nooha AI models is strictly prohibited and constitutes a breach of contract.
            </p>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl font-bold text-white tracking-tight">3. Data Integrity & Service Level</h2>
            <p className="text-zinc-500">
              Nooha Labs maintains a strict **99.9% uptime** standard for institutional cloud environments. Every Nooha ERP instance operates in a cryptographically isolated tenant space. While we maintain rigorous multi-region backup protocols, we are not liable for regional internet disruptions or upstream provider failures (GCP/Firebase) that fall outside our logical orchestration layer.
            </p>
          </section>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="pt-16 border-t border-[#1E293B]"
          >
             <h4 className="text-white font-black text-xl mb-4 tracking-tight">Compliance & Inquiries</h4>
             <p className="text-sm mb-8 text-zinc-500">For questions regarding your institutional license, data processing addendums, or terms of service, please contact our legal team:</p>
             <div className="inline-flex items-center gap-3 px-6 py-3 rounded-xl bg-[#111827] border border-[#1E293B] font-mono text-emerald-500 text-sm hover:border-emerald-500/40 transition-colors">
                compliance@noohalabs.com
             </div>
          </motion.div>
        </div>
      </Container>
    </Section>
  );
}
